### ISSUE TITLE
(1.19.2) Enchanted books don't show up

### ISSUE THREAD

**Issue by ANormalRaft** [HyperPigeon/Better-Wandering-Trader#11]
(1.19.2)
I attempted to add enchanted books to the "user_added_traded" (specifically mending) and the wandering traders spawned only once with it. All other 20-ish traders spawned (with an egg) didn't have it. Adding normal items to the array still works. I based the identifier of the mending book off of the syntax of the /give command, so maybe there is a syntax for enchanted books that I don't know about or it just doesn't work.

I just want to know which is true :)

![enchanted_book](https://user-images.githubusercontent.com/121328293/216746876-96c6e809-c60f-4a39-b45c-b19ed1f2657a.png)

**Comment by HyperPigeon** [comment]
I don't think you're using the correct identifier. Also, I'm planning on overhauling the codebase for this mod to make it easier for people to use since it's currently quite confusing to try and add new trades. It might be worth waiting for the refactored version of Better Wandering Traders before you add custom trades.

**Comment by ANormalRaft** [comment]
Thanks for the reply <3
